upstream node_apps {
    server web:3000;
}

server {
    listen 80;
    server_name main_server;

    location / {
        proxy_pass http://node_apps;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }
}